<?php

namespace App\Models\Traits;
use Ramsey\Uuid\Uuid as RamseyUuid;

trait Uuid
{
  public static function boot()
    {
        parent::boot(); // Changes the autogenerated stub
        static::creating(function($obj){ // before creating
            $obj->id = RamseyUuid::uuid4()->toString();
        });
    }
}
